"""empty message

Revision ID: 0ce6d0ea1214
Revises: 1634ddaeccd3
Create Date: 2019-12-24 16:30:12.125815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce6d0ea1214'
down_revision = '1634ddaeccd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurseschedule',
    sa.Column('nurseID', sa.CHAR(length=4), nullable=False),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['nurseID'], ['medicalstaff.StaffID'], ),
    sa.PrimaryKeyConstraint('nurseID', 'startDate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nurseschedule')
    # ### end Alembic commands ###
