"""empty message

Revision ID: 1634ddaeccd3
Revises: bc4ce7769ff8
Create Date: 2019-12-24 00:25:54.956027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1634ddaeccd3'
down_revision = 'bc4ce7769ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nurseschedule')
    op.add_column('hspapply', sa.Column('arrangeStatus', sa.CHAR(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hspapply', 'arrangeStatus')
    op.create_table('nurseschedule',
    sa.Column('nurseID', mysql.CHAR(collation='utf8_bin', length=4), nullable=False),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['nurseID'], ['medicalstaff.StaffID'], name='nurseschedule_ibfk_1'),
    sa.PrimaryKeyConstraint('nurseID', 'startDate'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
