"""empty message

Revision ID: 228e22340dbe
Revises: 
Create Date: 2019-12-21 15:38:39.028416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228e22340dbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed',
    sa.Column('bedNo', sa.CHAR(length=4), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bedNo')
    )
    op.create_table('department',
    sa.Column('department_ID', sa.CHAR(length=3), nullable=False),
    sa.Column('departmentName', sa.CHAR(length=30), nullable=True),
    sa.Column('doctor_ID', sa.CHAR(length=4), nullable=True),
    sa.Column('nurse_ID', sa.CHAR(length=4), nullable=True),
    sa.PrimaryKeyConstraint('department_ID')
    )
    op.create_table('medicalstaff',
    sa.Column('StaffID', sa.CHAR(length=4), nullable=False),
    sa.Column('name', sa.CHAR(length=20), nullable=True),
    sa.Column('gender', sa.CHAR(length=10), nullable=True),
    sa.Column('entryDay', sa.DATE(), nullable=True),
    sa.Column('retirementDate', sa.DATE(), nullable=True),
    sa.Column('phoneNumber', sa.CHAR(length=11), nullable=True),
    sa.Column('officeNo', sa.CHAR(length=10), nullable=True),
    sa.Column('position', sa.CHAR(length=20), nullable=True),
    sa.Column('email', sa.CHAR(length=20), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.CHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('StaffID')
    )
    op.create_table('medicine',
    sa.Column('medicineID', sa.CHAR(length=3), nullable=False),
    sa.Column('m_name', sa.CHAR(length=20), nullable=True),
    sa.Column('company', sa.CHAR(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('inDate', sa.DATE(), nullable=True),
    sa.Column('expireDate', sa.DATE(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('medicineID')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.CHAR(length=20), nullable=True),
    sa.Column('gender', sa.CHAR(length=10), nullable=True),
    sa.Column('birthDay', sa.DATE(), nullable=True),
    sa.Column('phoneNumber', sa.CHAR(length=50), nullable=True),
    sa.Column('address', sa.CHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription',
    sa.Column('prescriptionID', sa.CHAR(length=5), nullable=False),
    sa.Column('prescriptionDate', sa.DATE(), nullable=True),
    sa.Column('paymentStatues', sa.CHAR(length=1), nullable=True),
    sa.Column('giveStatues', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('prescriptionID')
    )
    op.create_table('reservation',
    sa.Column('reservationID', sa.CHAR(length=4), nullable=False),
    sa.Column('reservationDate', sa.DATE(), nullable=True),
    sa.Column('reservationTime', sa.Integer(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('reservationID')
    )
    op.create_table('ward',
    sa.Column('wardNo', sa.CHAR(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('wardNo')
    )
    op.create_index(op.f('ix_ward_wardNo'), 'ward', ['wardNo'], unique=False)
    op.create_table('schedule',
    sa.Column('staff_ID', sa.CHAR(length=4), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('timeInterval8', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval9', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval10', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval11', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval14', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval15', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval16', sa.CHAR(length=1), nullable=True),
    sa.Column('timeInterval17', sa.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['staff_ID'], ['medicalstaff.StaffID'], ),
    sa.PrimaryKeyConstraint('staff_ID', 'date')
    )
    op.create_table('warehouse',
    sa.Column('warehouseID', sa.CHAR(length=2), nullable=False),
    sa.Column('warehouseadmin_ID', sa.CHAR(length=4), nullable=True),
    sa.ForeignKeyConstraint(['warehouseadmin_ID'], ['medicalstaff.StaffID'], ),
    sa.PrimaryKeyConstraint('warehouseID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_ward_wardNo'), table_name='ward')
    op.drop_table('ward')
    op.drop_table('reservation')
    op.drop_table('prescription')
    op.drop_table('patient')
    op.drop_table('medicine')
    op.drop_table('medicalstaff')
    op.drop_table('department')
    op.drop_table('bed')
    # ### end Alembic commands ###
