"""empty message

Revision ID: 5def485aaa81
Revises: f70996347fb7
Create Date: 2019-12-21 16:50:28.906120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5def485aaa81'
down_revision = 'f70996347fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('department_ibfk_2', 'department', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('department_ibfk_2', 'department', 'medicalstaff', ['nurse_ID'], ['StaffID'])
    # ### end Alembic commands ###
