"""empty message

Revision ID: 6b983e2d4d63
Revises: 0ce6d0ea1214
Create Date: 2019-12-24 21:00:58.364201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b983e2d4d63'
down_revision = '0ce6d0ea1214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('postContent', sa.CHAR(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'postContent')
    # ### end Alembic commands ###
