"""empty message

Revision ID: 861191fbf9ce
Revises: 9c33f6742602
Create Date: 2019-12-21 15:54:08.705605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861191fbf9ce'
down_revision = '9c33f6742602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hspapply', sa.Column('id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hspapply', 'patient', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hspapply', type_='foreignkey')
    op.drop_column('hspapply', 'id')
    # ### end Alembic commands ###
