"""empty message

Revision ID: b3deab6435c9
Revises: d0afe73fc0d3
Create Date: 2019-12-22 23:02:07.255852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3deab6435c9'
down_revision = 'd0afe73fc0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospitalization', 'bedNo',
               existing_type=mysql.CHAR(collation='utf8_bin', length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospitalization', 'bedNo',
               existing_type=mysql.CHAR(collation='utf8_bin', length=4),
               nullable=False)
    # ### end Alembic commands ###
