"""empty message

Revision ID: bc4ce7769ff8
Revises: 56b39070bc4a
Create Date: 2019-12-23 19:31:56.398911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc4ce7769ff8'
down_revision = '56b39070bc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurseschedule',
    sa.Column('nurseID', sa.CHAR(length=4), nullable=False),
    sa.Column('endDate', sa.DATE(), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['nurseID'], ['medicalstaff.StaffID'], ),
    sa.PrimaryKeyConstraint('nurseID', 'startDate')
    )
    op.drop_column('hspapply', 'arrangeStatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hspapply', sa.Column('arrangeStatus', mysql.CHAR(collation='utf8_bin', length=1), nullable=True))
    op.drop_table('nurseschedule')
    # ### end Alembic commands ###
