"""empty message

Revision ID: d0afe73fc0d3
Revises: 0122df8413d5
Create Date: 2019-12-21 17:43:29.468539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0afe73fc0d3'
down_revision = '0122df8413d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hspapply', sa.Column('arrangeStatus', sa.CHAR(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hspapply', 'arrangeStatus')
    # ### end Alembic commands ###
