"""empty message

Revision ID: db1ce4e83875
Revises: 5def485aaa81
Create Date: 2019-12-21 16:59:11.312677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db1ce4e83875'
down_revision = '5def485aaa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalstaff', sa.Column('departmentID', sa.CHAR(length=3), nullable=True))
    op.drop_constraint('medicalstaff_ibfk_1', 'medicalstaff', type_='foreignkey')
    op.create_foreign_key(None, 'medicalstaff', 'department', ['departmentID'], ['department_ID'])
    op.drop_column('medicalstaff', 'department_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalstaff', sa.Column('department_ID', mysql.CHAR(collation='utf8_bin', length=3), nullable=True))
    op.drop_constraint(None, 'medicalstaff', type_='foreignkey')
    op.create_foreign_key('medicalstaff_ibfk_1', 'medicalstaff', 'department', ['department_ID'], ['department_ID'])
    op.drop_column('medicalstaff', 'departmentID')
    # ### end Alembic commands ###
