"""empty message

Revision ID: f70996347fb7
Revises: aa5470014f0a
Create Date: 2019-12-21 16:25:01.411552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70996347fb7'
down_revision = 'aa5470014f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'department', 'medicalstaff', ['doctor_ID'], ['StaffID'])
    op.create_foreign_key(None, 'department', 'medicalstaff', ['nurse_ID'], ['StaffID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    # ### end Alembic commands ###
